version: '3.8'

services:
  app:
    build: .
    container_name: rewear-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rewearSpring?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Priya@2312
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Priya@2312
      MYSQL_DATABASE: rewearSpring
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
